name: Build Variant Annotation
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  build-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get install -yq file tabix

      - name: "Download/Build"
        env:
          N_THREADS: 2
        run: |
          bash ./runInitializeTest.sh
