name: Build Variant Annotation
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  build-sources:
    runs-on: ubuntu-latest
    container:
      image: broadinstitute/gatk:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Install packages
        run: |
          wget https://packages.cloud.google.com/apt/doc/apt-key.gpg
          apt-key add apt-key.gpg
          apt-get update
          apt-get install -yq file tabix

      - name: "Download/Build"
        env:
          N_THREADS: 2
        run: |
          bash ./runInitializeTest.sh
